### ISSUE TITLE
Hold manager: removing aircraft

### ISSUE THREAD

**Issue by hsugden** [VATSIM-UK/uk-controller-plugin#179] opened 2020-11-15 12:43 UTC
As TC NE managing the LAM hold, for some reason a BAW1551 had ended up in the hold manager - a CPT departure from EGLL. Because the tag was assumed by someone else (I think TC SW), the hold manager would not let me remove him from the hold.

I don't think it would be wise to put a check on flightplans because you might have someone who after departure, requires to hold to fix a problem or something. But there does need to be a way of removing aircraft who shouldn't be there

**Comment by AndyTWF** [comment] 2020-11-16 17:32
Hi Harry, assuming you're referring to a time during CTP here? I can see that that aircraft was assigned by another controller to BRASO at `2020-11-14 19:59:47`, followed by you assigning it to LAM at `2020-11-14 20:19:16`. It looks like the aircraft then retained that hold until `2020-11-14 22:37:28` at which point the system detected the aircraft was offline and removed it.

What looks like happened is that the aircraft was not removed from LAM in the hold manager, then re-appeared as it climbed back out some time later on. This is expected behaviour as the aircraft was still officially holding and it would also follow that you would be prevented from removing him as you weren't tracking.

Perhaps we could add something to UKCP API that automatically removes the aircraft from the hold if it's detected to have landed?

In terms of changes to who can remove aircraft from the hold - happy to accept suggestions. I deliberately designed it so that you couldn't get random controllers / observers being a pain and taking aircraft out of the hold for the fun of it but happy to explore options :)

**Comment by hsugden** [comment] 2020-11-23 13:35
Yes, the difficulty arises when London uses Hold Manager, but Heathrow doesn't for example - when the a/c leaves the hold, there is no way for London to remove it! A descent at least 2 levels below the lowest holding level / the aircraft disconnecting / the aircraft landing all sound like sensible triggers to remove them - but perhaps the 'time elapsed' in the hold can be stored somewhere for 10 minutes or so, in case of their return?

**Comment by AndyTWF** [comment] 2021-06-11 15:58
Hi @hsugden - this has been implemented on the API side.

We now remove aircraft from holds if they land, or if they drift over a certain distance (30nm) from the holding fix.

**Closed by AndyTWF** 2021-06-11 15:58 UTC
Labels: bug, question
